# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformRoulette < Formula
  desc "Terraform CLI if it was inspired by roulette"
  homepage "https://github.com/lbennett-stacki/terraform-roulette"
  version "0.0.5"
  license "MIT"

  depends_on "go"
  depends_on "terraform"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/<repo_owner>/<repo_name>/releases/download/v0.0.5/terraform-roulette_Darwin_x86_64.tar.gz"
      sha256 "9c5b004fa25c0a730d94c3b870bbe59a328e0daaca74fe0a006e8162e986cdcc"

      def install
        bin.install "terraform-roulette"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/<repo_owner>/<repo_name>/releases/download/v0.0.5/terraform-roulette_Darwin_arm64.tar.gz"
      sha256 "da3465f15162d3eb47255f71305e02e3c340e71c54582cb95fe6dc3ee6995cbf"

      def install
        bin.install "terraform-roulette"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/<repo_owner>/<repo_name>/releases/download/v0.0.5/terraform-roulette_Linux_x86_64.tar.gz"
      sha256 "89ccb479795e86a7e49b73739a684e82f0ee5c781b927192d950b886de60fdcf"

      def install
        bin.install "terraform-roulette"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/<repo_owner>/<repo_name>/releases/download/v0.0.5/terraform-roulette_Linux_arm64.tar.gz"
      sha256 "05514d005c2f5a60e796d1fa4ad4ad3c7f3ae0055b46de2d0e7cdcbad4325cc3"

      def install
        bin.install "terraform-roulette"
      end
    end
  end
end
