# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformRoulette < Formula
  desc "Terraform CLI if it was inspired by roulette"
  homepage "https://github.com/lbennett-stacki/terraform-roulette"
  version "0.0.6"
  license "MIT"

  depends_on "go"
  depends_on "terraform"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lbennett-stacki/terraform-roulette/releases/download/v0.0.6/terraform-roulette_Darwin_x86_64.tar.gz"
      sha256 "f023913d939b5248c9cf7764c972d34e683d3747ccfbba8b9bdb5e6f133a4128"

      def install
        bin.install "terraform-roulette"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lbennett-stacki/terraform-roulette/releases/download/v0.0.6/terraform-roulette_Darwin_arm64.tar.gz"
      sha256 "584ecfc8fcdf5b2134de58c183b845b69145932c2616f4163e27c0573c7c4556"

      def install
        bin.install "terraform-roulette"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lbennett-stacki/terraform-roulette/releases/download/v0.0.6/terraform-roulette_Linux_x86_64.tar.gz"
      sha256 "f3381e9bf98be5e4790b803b7677e5f347fbc47c03698f224ee7b13f0260c6b6"

      def install
        bin.install "terraform-roulette"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lbennett-stacki/terraform-roulette/releases/download/v0.0.6/terraform-roulette_Linux_arm64.tar.gz"
      sha256 "ac52edc7e711d77b30a3617afa01b80340c440d45656601a9775aafe5429a79f"

      def install
        bin.install "terraform-roulette"
      end
    end
  end
end
