# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformRoulette < Formula
  desc "Terraform CLI if it was inspired by roulette"
  homepage "https://github.com/lbennett-stacki/terraform-roulette"
  version "0.0.3"
  license "MIT"

  depends_on "go"
  depends_on "terraform"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/<repo_owner>/<repo_name>/releases/download/v0.0.3/terraform-roulette_Darwin_x86_64.tar.gz"
      sha256 "bd903e093033da5c1f592221d101679dc0a7b1715eff57222853b28bd0e01bb0"

      def install
        bin.install "terraform-roulette"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/<repo_owner>/<repo_name>/releases/download/v0.0.3/terraform-roulette_Darwin_arm64.tar.gz"
      sha256 "0b099d64910f2bd64b68c5ae51f3ece8983cfd63760ddca0826d2232bde173dc"

      def install
        bin.install "terraform-roulette"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/<repo_owner>/<repo_name>/releases/download/v0.0.3/terraform-roulette_Linux_x86_64.tar.gz"
      sha256 "a8f6624aef6d3f9a57a07d733bdaec2b1d42ee082ffeb0ec321ee43e7b66aa17"

      def install
        bin.install "terraform-roulette"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/<repo_owner>/<repo_name>/releases/download/v0.0.3/terraform-roulette_Linux_arm64.tar.gz"
      sha256 "3cc1ce22b5c8d9d1f03cb5fcfa165c602b7b0122fb6f55c860daaf43d42f7af7"

      def install
        bin.install "terraform-roulette"
      end
    end
  end
end
