# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformRoulette < Formula
  desc "Terraform CLI if it was inspired by roulette"
  homepage "https://github.com/lbennett-stacki/terraform-roulette"
  version "0.0.9"
  license "MIT"

  depends_on "go"
  depends_on "terraform"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lbennett-stacki/terraform-roulette/releases/download/v0.0.9/terraform-roulette_Darwin_x86_64.tar.gz"
      sha256 "9af84ad3f8e78d6d8ea16ac8f9d5d376b6580f067fac277f2defba4adbc090ef"

      def install
        bin.install "terraform-roulette"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lbennett-stacki/terraform-roulette/releases/download/v0.0.9/terraform-roulette_Darwin_arm64.tar.gz"
      sha256 "58bcd5546b03759cb4b5dafcee61566500467a5b000392d3c13074d25bb60d52"

      def install
        bin.install "terraform-roulette"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lbennett-stacki/terraform-roulette/releases/download/v0.0.9/terraform-roulette_Linux_x86_64.tar.gz"
      sha256 "5a7595d3a036a55b4a99647bd91ba3f780466ba637383c86667cb2752c7e182b"

      def install
        bin.install "terraform-roulette"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lbennett-stacki/terraform-roulette/releases/download/v0.0.9/terraform-roulette_Linux_arm64.tar.gz"
      sha256 "1da813f6518d5571b0ce6f9c63e2644cd12cc079817c1bc51958e28c533b6925"

      def install
        bin.install "terraform-roulette"
      end
    end
  end
end
