# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformRoulette < Formula
  desc "Terraform CLI if it was inspired by roulette"
  homepage "https://github.com/lbennett-stacki/terraform-roulette"
  version "0.0.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lbennett-stacki/terraform-roulette/releases/download/v0.0.12/terraform-roulette_Darwin_x86_64.tar.gz"
      sha256 "21f96a5357ec200eec18ee0b087250a50515b7289236773f3d46b9dbadca37cf"

      def install
        bin.install "terraform-roulette"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lbennett-stacki/terraform-roulette/releases/download/v0.0.12/terraform-roulette_Darwin_arm64.tar.gz"
      sha256 "21cb743f8ba33df4eaf342e185a0b241ffe6fc0e9c69342d5a95f3eb836bd58f"

      def install
        bin.install "terraform-roulette"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lbennett-stacki/terraform-roulette/releases/download/v0.0.12/terraform-roulette_Linux_x86_64.tar.gz"
      sha256 "65f1666ebc68ce22f20ac84442d9b0ed321db319ace82d3676899127a33c31cc"

      def install
        bin.install "terraform-roulette"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lbennett-stacki/terraform-roulette/releases/download/v0.0.12/terraform-roulette_Linux_arm64.tar.gz"
      sha256 "e1d115681ed718cd3f13d781a8d7c6e784858a47bd36c9befc89f438cdc277e6"

      def install
        bin.install "terraform-roulette"
      end
    end
  end
end
