# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerraformRoulette < Formula
  desc "Terraform CLI if it was inspired by roulette"
  homepage "https://github.com/lbennett-stacki/terraform-roulette"
  version "0.0.13"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lbennett-stacki/terraform-roulette/releases/download/v0.0.13/terraform-roulette_Darwin_x86_64.tar.gz"
      sha256 "23cb8e6815bfea72ce6f0be46a1fc26564fd61fad6dba812670fe256834c1fd9"

      def install
        bin.install "terraform-roulette"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lbennett-stacki/terraform-roulette/releases/download/v0.0.13/terraform-roulette_Darwin_arm64.tar.gz"
      sha256 "329b9f23635684ee7e1f056401099574eb6c818dd410cf2dd3770aa51c1bffee"

      def install
        bin.install "terraform-roulette"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lbennett-stacki/terraform-roulette/releases/download/v0.0.13/terraform-roulette_Linux_x86_64.tar.gz"
      sha256 "82481d0416dd78a793a671abf6bec30c3d94c2da19d474f79d4eac635061d730"

      def install
        bin.install "terraform-roulette"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lbennett-stacki/terraform-roulette/releases/download/v0.0.13/terraform-roulette_Linux_arm64.tar.gz"
      sha256 "8be90579827208ea1cbd723c5048ccc05bfcb0a7d79340754007cc4f52c522d8"

      def install
        bin.install "terraform-roulette"
      end
    end
  end
end
